export type Language = 'zh' | 'en'
export type Bilingual = { zh: string; en: string }
export const words = (zh: string, en: string): Bilingual => ({ zh, en })
export type Parameter = { key: string; label: Bilingual; help: Bilingual; placeholder?: string; flag?: boolean }
const field = (key: string, zh: string, en: string, helpZh: string, helpEn: string, placeholder?: string): Parameter => ({ key, label: words(zh,en), help: words(helpZh,helpEn), placeholder })
const flag = (key: string, zh: string, en: string, helpZh: string, helpEn: string): Parameter => ({ ...field(key,zh,en,helpZh,helpEn), flag:true })
export const identityHelp = {
  name: words('用于托盘菜单和配置列表的显示名称，可与 API model ID 不同。重命名不会移动模型文件。', 'The display name in the tray and profile list. It may differ from the API model ID. Renaming does not move the model file.'),
  model: words('选择已扫描到的 .ninfer 主文件。引擎启动时才加载权重到 GPU；扫描不会加载 GPU。相对路径从模型包根目录解析。更换文件后应核对上下文和量化格式。', 'Choose the scanned .ninfer entry file. GPU weights are loaded only when the engine starts; scanning does not load the GPU. Relative paths start at the package root. Check context and quantization when changing models.'),
  engine: words('实际运行的 ninfer-serve.exe 路径；相对路径从模型包根目录解析。不同引擎支持的参数可能不同。当前 engine 目录中的版本支持严格驻留检查。', 'Path to the ninfer-serve.exe to run, relative to the package root or absolute. Supported options depend on the engine. The build in the engine directory supports strict residency checks.'),
  json: words('直接编辑完整 CLI 参数字典：键为 --参数名，字符串为参数值，null 表示只传这个开关，删除键表示不传。高级模式保存前会验证 JSON 对象；切换语言不会改变内容。管理器生成请求日志路径。未知参数的语义请查所选引擎 --help。', 'Edit the complete CLI argument object: keys are --option names, strings are values, null passes a flag without a value, and deleting a key omits it. JSON is validated before saving. Changing language does not change this text. The manager generates the request-log path. Consult the selected engine’s --help for unknown options.'),
  environment: words('仅为模型子进程设置环境变量；字符串覆盖，null 清除继承值。NINFER_PREFILL_ALIGN=0 保持填写的 chunk；NINFER_PROMPT_FAST 影响 prompt 内核选择；CUDA_LAUNCH_BLOCKING=1 强制同步，通常会变慢。不要把未知变量当作性能开关。', 'Environment overrides for the model process only: strings set a value; null removes an inherited value. NINFER_PREFILL_ALIGN=0 keeps the requested chunk. NINFER_PROMPT_FAST affects prompt-kernel selection. CUDA_LAUNCH_BLOCKING=1 forces synchronization and usually slows execution. Unknown variables are not assumed to improve performance.'),
}
export const strictMemoryHelp = {
  reserve: words('严格模式启动时额外申请并验证的显存余量，随后释放。增大可给运行留出更多空间，但可用 KV 容量减少；0 不额外验证余量。它不限制 Host cache。默认 64 MiB，对应 strict 的第一个数字。','Extra VRAM allocated and verified at startup in strict mode, then released. More headroom leaves operating room but reduces KV capacity; zero skips the extra reserve check. It does not limit Host cache. The default is 64 MiB, the first number in strict.'),
  step: words('严格模式自动容量探测在初始大块后以这个步长逼近边界，范围 1–16384 MiB。更小更细但探测可能更慢，0 无效。正式 device arena 仍是连续分配。默认 128 MiB，对应 strict 的第二个数字。','After the initial large allocation, strict-mode automatic capacity probing approaches the boundary with this step, from 1 to 16384 MiB. Smaller steps are finer but may be slower; zero is invalid. Final device arenas remain contiguous. The default is 128 MiB, the second number in strict.'),
}
export const groups: { title:Bilingual; fields:Parameter[] }[] = [
 { title:words('API 与上下文','API and context'), fields:[
  field('--model-id','API 模型名称','API model ID','客户端请求中的 model 字段必须使用这个名称。多个配置可以共用一个名称，但本管理器同时只启动一个模型。修改不会重命名权重文件。','Clients use this name in the request’s model field. Profiles may share a name; this manager runs one model at a time. It does not rename model files.'),
  field('--host','API 监听地址','API host','本地 API 的监听地址。管理器支持 127.0.0.1 或 localhost，仅供本机访问；这不是管理网页地址。','The model API bind address. This manager accepts 127.0.0.1 or localhost for local access. It is separate from the management web address.','127.0.0.1'),
  field('--port','API 端口','API port','客户端连接模型的端口，范围 1–65535。需与管理网页端口及其他进程不同；更改后客户端也需要更新 API base。0 不是自动选端口。','The model API port, from 1 to 65535. It must differ from the management port and other listeners. Update clients’ API base after changing it. Zero does not select a port automatically.','18081'),
  field('--max-context','最大上下文 · tokens','Context limit · tokens','单个请求可容纳的总 token 上限，包含输入、历史、思考和回答；1K=1024。增大通常需要更多 KV 显存。0 无效。这里单独编辑上下文，不自动改 KV 容量，请确保 KV 容量足够。','The per-request total token ceiling, including input, history, reasoning and answer; 1K=1024. Increasing it generally needs more KV memory. Zero is invalid. This field does not rewrite KV capacity; make sure the pool covers it.','163840'),
  field('--kv-capacity','KV 池容量 · tokens / auto','KV capacity · tokens / auto','物理 KV 缓存总容量，应不小于最大上下文，按 64-token 页对齐。auto 随显存策略规划：default 按 CUDA free，strict 做驻留探测；mixed 最多规划每并发一个完整上下文窗口，不额外填满空闲前缀缓存。增大容量增加内存占用。0 无效，auto 不提高单请求上下文上限，也不保证分配成功。','Physical KV capacity must cover the context limit and rounds to 64-token pages. With auto, default uses CUDA free, strict probes residency, and mixed budgets at most one full context window per concurrent request, without filling extra prefix-cache space. More capacity uses more memory. Zero is invalid. Auto neither raises the context limit nor guarantees successful allocation.','163840 / auto'),
  field('--max-concurrency','并行请求数','Concurrent requests','同时执行的请求数，范围 1–8。单个 Codex agent 通常设 1；增大会增加状态与显存开销，可能降低单请求速度。ngram 草稿大于 15 时必须为 1。0 无效。','Requests executed together, from 1 to 8. One Codex agent usually uses 1. Higher values require more state and VRAM and may reduce single-request speed. Ngram drafts above 15 require 1. Zero is invalid.','1'),
  field('--default-max-tokens','默认最大输出 · tokens','Default output limit · tokens','仅在请求没有显式指定输出上限时使用；思考和回答都计入输出。0 不设独立输出上限，仍受剩余上下文限制，并非无限上下文。较小值可控制等待时间，但可能截断回答。','Used only when a request omits its output limit. Both reasoning and answer tokens count. Zero removes this separate cap but generation still ends when context is exhausted. Smaller limits shorten waits but may truncate an answer.','0'),
 ]},
 { title:words('显存与缓存','GPU memory and cache'), fields:[
  field('--prefill-chunk','预填充块大小 · tokens','Prefill chunk · tokens','每批读取多少输入 token，应为 128 的倍数。更大可能提高预填充吞吐，也增加临时显存；更小可能降低峰值占用，但不一定更快。0 无效。是否自动对齐还受 NINFER_PREFILL_ALIGN 影响。','Input tokens processed per chunk; use a multiple of 128. Larger chunks may improve prefill throughput but require more temporary VRAM. Smaller chunks may reduce peaks, not necessarily latency. Zero is invalid. NINFER_PREFILL_ALIGN controls automatic alignment.','256 / 640'),
  field('--kv-dtype','KV 缓存格式','KV cache format','保存注意力历史的格式。rk8v4 是当前已验证路线；rk4v4 / rk4v4-e8 更省显存，但精度和性能需要实测。更换会影响容量及缓存兼容性，不会改变权重量化文件。','Storage format for attention history. rk8v4 is the currently validated route. rk4v4 / rk4v4-e8 use less VRAM but need quality and speed validation. Changing it affects cache size and compatibility, not the weight file.','rk8v4'),
  field('--cuda-memory-policy','显存分配策略','GPU memory policy','default 保持 CUDA free 容量规划和原分配行为，也不保证绝不使用共享系统内存。mixed 允许超过 CUDA free 尝试分配；显存不足时允许 Windows 用系统内存承接 CUDA 设备数据，驱动决定放置，并非强制分配到 Shared。可能变慢，分配仍可能失败。strict 自动选择所需上下文缓存实现并检查实际驻留，Shared 超出基线会拒绝容量或后续请求。strict 默认余量/步长为 64/128 MiB，也可使用 strict-N-N。mixed/strict 仅支持 Windows 单 GPU 纯文本，不能与 WDDM D3D12 或显式 KV headroom 参数组合。CPU Host cache 独立配置，不属于显存不足时的系统内存借用。','default keeps CUDA-free capacity planning and the original allocation behavior; it does not guarantee that shared system memory will never be used. mixed may attempt allocation beyond CUDA free. When VRAM is insufficient, Windows may use system RAM for CUDA device data; the driver decides placement, rather than forcing allocation into Shared. Performance may decrease and allocation may still fail. strict automatically selects the required context-cache implementation and checks residency, rejecting capacity or later requests if Shared exceeds its baseline. strict uses a 64/128 MiB reserve/step by default, or strict-N-N. mixed/strict require Windows, one GPU and text-only inference and cannot use WDDM D3D12 or explicit KV headroom options. CPU Host cache is independent and is not system-RAM borrowing caused by insufficient VRAM.','strict'),
  field('--cuda-graph-allowance-mib','Graph 启动预算 · MiB','Graph startup budget · MiB','容量规划为 CUDA Graph 驱动状态预留的预算，不是 Graph 实际显存上限，也不会把 Graph 强制压到此大小。0 表示按执行路线自动估算；减小可释放规划预算，但可能使启动布局太紧。','Budget withheld during capacity planning for CUDA Graph driver state. It is neither a hard cap nor a command to shrink Graph allocations. Zero estimates it from execution profiles. Reducing it frees planned capacity but may make startup too tight.','72'),
  field('--host-cache-mib','主机缓存预算 · MiB','Host cache budget · MiB','使用 CPU 内存保存可复用 KV 和状态快照，不是 GPU 显存扩容。更大可保留更多前缀，但增加锁页 RAM 和传输开销；0 不建立 Host tier。Windows Shared 基线可能包含这部分。','CPU RAM for reusable KV and state snapshots, not extra GPU capacity. More retains more prefixes but consumes pinned RAM and transfer work. Zero disables the Host tier. This allocation may appear in the Windows Shared baseline.','6144'),
  field('--device-snapshot-slots','GPU 状态快照槽位','GPU snapshot slots','混合前缀缓存保留的 GPU 状态快照数量，范围 1–64，0 无效。增大可能提高分支复用机会，同时增加显存占用；留空时由并发及 Host tier 决定默认值。','GPU state snapshots retained by the hybrid cache, from 1 to 64; zero is invalid. More slots may improve branch reuse but consume VRAM. When omitted, the default depends on concurrency and the Host tier.','1'),
  flag('--gdn-state-fp16','GDN 状态使用 FP16','FP16 GDN state','用 FP16 保存循环状态，减少该部分设备与主机快照内存。关闭恢复默认精度，内存可能增加。它改变状态存储精度，不会将模型权重转换成 FP16。','Stores recurrent state in FP16, reducing that part of GPU and host snapshot memory. Disabling restores the default precision and may increase memory use. This affects state storage, not model weight precision.'),
 ]},
 { title:words('草稿加速','Speculative decoding'), fields:[
  field('--spec','草稿后端','Draft backend','mtp 使用模型内置 MTP 组件生成草稿，再由主模型验证；清空此字段表示不传 --spec，即关闭草稿后端。dflash / dflash2 需要相应模型组件。开启不保证更快，效果取决于接受率。','mtp uses the built-in MTP component to propose tokens for verification by the main model. Clear the field to omit --spec and disable the draft backend. dflash / dflash2 need matching components. Speed depends on acceptance; enabling it is not a guaranteed gain.','mtp'),
  field('--draft-tokens','每轮 MTP 草稿数','MTP drafts per round','每轮提出的 token 数，范围 1–15。更多草稿有机会一次接受更多 token，也增加草稿和验证开销；2 是当前配置。0 不是关闭开关，请清空草稿后端来关闭。','Tokens proposed per round, from 1 to 15. More drafts may accept more tokens at once but add proposal and verification work. The current profile uses 2. Zero is not the off switch; clear the draft backend to disable it.','2'),
  field('--ngram-draft-tokens','复制草稿上限','Ngram draft limit','从已出现的提示、工具输出或回答中复制匹配片段，再验证。代码复制场景可能获益。范围 1–63，0 关闭；超过 15 只支持单并发。更大不代表接受率更高。','Copies matched text from prior prompt, tool output or generated text, then verifies it. Code-copy workloads may benefit. Use 1–63; zero disables it. Values above 15 require one concurrent request. Longer drafts do not guarantee higher acceptance.','31'),
  field('--mtp-attention-window','MTP 注意力窗口 · tokens','MTP attention window · tokens','MTP 草稿只看最前 64 个 key 与最近 N 个 key；主模型验证仍使用完整上下文。0 使用全部历史。较小窗口可能减少草稿工作量，也可能降低草稿接受率，需要长上下文实测。','The MTP draft head attends to its first 64 keys and the latest N keys; main-model verification still sees full context. Zero uses all history. Smaller windows may reduce draft work but lower acceptance, so validate long-context performance.','0'),
  flag('--lm-head-draft','优化草稿输出头','Optimized draft head','使用优化的 proposal head 生成草稿。是否更快取决于模型及内核路线；当前最终配置关闭。不会改变主模型最终验证的流程。','Uses the optimized proposal head for drafts. Speed depends on the model and kernel route; the current final profile leaves it off. Main-model verification remains in place.'),
 ]},
 { title:words('采样与思考','Sampling and reasoning'), fields:[
  field('--temperature','随机程度 · Temperature','Temperature','范围 0–2。较高通常更随机，较低更集中；0 选择最高概率 token。服务默认值可被请求覆盖，不是直接的速度档位。','Range 0–2. Higher is generally more random, lower more focused; zero picks the highest-probability token. Requests may override this default. It is not a direct speed setting.','1.0'),
  field('--top-p','累计概率 · Top P','Top P','范围 0–1，只保留累计概率达到阈值的候选。降低通常收窄选择；1 不做这项截断。0 是极窄阈值，不是关闭；与其他采样过滤共同作用。','Range 0–1. Keeps candidates up to a cumulative-probability threshold. Lower values narrow choices; 1 removes this cutoff. Zero is an extremely narrow threshold, not off. It combines with other sampling filters.','0.95'),
  field('--top-k','候选数量 · Top K','Top K','保留最可能的 K 个候选，本引擎范围 0–20。较小更集中；0 禁用 Top K 筛选。不会增加模型上下文或显存容量。','Keeps the K most likely candidates; this engine accepts 0–20. Smaller values focus sampling; zero disables Top K. It does not increase context or VRAM capacity.','20'),
  field('--min-p','相对概率 · Min P','Min P','范围 0–1，以最高概率候选为参照删除过低概率候选。增大过滤更强；0 关闭这项过滤。与 Top P / Top K 同时生效。','Range 0–1. Removes candidates whose probability is too small relative to the best candidate. Higher means stronger filtering; zero disables it. It combines with Top P and Top K.','0'),
  field('--presence-penalty','出现惩罚','Presence penalty','范围 -2–2。正值抑制已经出现过的 token，负值更鼓励再次出现；0 不加惩罚。代码中的必要重复也可能受影响，不建议为追求速度而提高。','Range -2–2. Positive values discourage previously seen tokens; negative values encourage repetition. Zero adds no penalty. Necessary code repetition can be affected; raising it is not a speed optimization.','0'),
  field('--frequency-penalty','频次惩罚','Frequency penalty','范围 -2–2，按 token 已出现次数施加惩罚。正值更强地抑制频繁重复，负值鼓励；0 不加惩罚。与 presence penalty 不是同一个规则。','Range -2–2. Applies a penalty based on how often a token has appeared. Positive values discourage frequent repetition, negative values encourage it, and zero adds none. This differs from presence penalty.','0'),
  field('--seed','默认随机种子','Default random seed','请求未指定 seed 时使用。固定值便于对比相同输入；0 也是固定种子，不是随机。清空表示每个请求重新生成种子。GPU执行等因素仍可能影响复现。','Used when a request omits its seed. A fixed value helps compare identical inputs. Zero is also a fixed seed, not random. Clear it for a fresh seed per request. GPU execution and other factors may still affect reproducibility.','42'),
  field('--default-reasoning-effort','默认思考强度','Default reasoning effort','客户端未指定时的思考级别，例如 low、medium、high、xhigh。较高通常允许更多推理，但不保证准确率或固定思考长度；仍受输出和上下文上限约束。实际行为依模型模板。','Reasoning level when the client omits it, such as low, medium, high or xhigh. Higher generally allows more reasoning but guarantees neither accuracy nor a fixed length. Output and context limits still apply. Exact behavior depends on the model template.','xhigh'),
  flag('--preserve-thinking','保留历史思考','Preserve previous reasoning','在模板允许的情况下保留历史思考内容供后续请求使用，有助于维持推理上下文，但会占用更多输入 token。关闭不等于禁止模型本轮思考。','Retains previous reasoning where the template allows it. This may preserve reasoning context but consumes more input tokens. Disabling it does not turn off reasoning for the current request.'),
 ]},
 { title:words('模板与设备路线','Template and device routes'), fields:[
  field('--chat-template','对话模板路径','Chat template path','启动时替换模型自带 Jinja 对话模板，影响角色、工具调用和思考内容的组织。清空使用模型内置模板。config/ 开头的相对路径使用当前数据目录中的配置；其他相对路径从程序目录解析，绝对路径保持原样。错误模板可能导致请求被拒绝。','Replaces the embedded Jinja chat template at startup, controlling roles, tool calls and reasoning formatting. Clear it to use the embedded template. Relative config/ paths use the active data directory; other relative paths start at the package root, and absolute paths are unchanged. Invalid templates may reject requests.','config/chat_template.jinja'),
  field('--device-profile','设备路线选择','Device profile mode','auto 使用已有设备 profile 或内置路线，设备没有 profile 时可校准；off 使用编译内置路线；calibrate 重新测量并保存。校准会增加启动耗时，也不保证更快。','auto uses a stored or built-in profile and may calibrate an unknown device. off uses compiled routes. calibrate measures and saves new routes. Calibration increases startup time and does not guarantee better performance.','auto'),
  field('--device-profile-path','设备 profile 文件','Device profile file','保存或读取 GPU 内核选择的文件。当前独立副本保留已验证路线；换文件可能改变内核选择和性能。config/ 开头的相对路径使用当前数据目录；绝对路径保持原样。清空由引擎使用默认用户缓存位置。','File for GPU kernel-route profiles. The current independent copy preserves validated routes. A different file may change kernel selection and performance. Relative config/ paths use the active data directory; absolute paths are unchanged. Clear it to use the engine’s default user-cache location.','config/device-profiles.json'),
 ]},
]
